/* auto-generated by NAPI-RS */
/* eslint-disable */
export type JsVariant =
  boolean | string | number | bigint

export interface ScopedEventFieldRef {
  field: string
}

export type ScopedEventFilterValue = JsVariant | ScopedEventFieldRef

export interface ScopedEventTickFilter {
  field: string
  op: 'eq' | 'neq' | 'in'
  value?: ScopedEventFilterValue
  values?: Array<ScopedEventFilterValue>
}

export interface ScopedEventSpec {
  event: string
  playerProps?: Array<string>
  otherProps?: Array<string>
  where?: Record<string, JsVariant>
  includeAllPlayers?: boolean
  tickFilter?: ScopedEventTickFilter | Array<ScopedEventTickFilter>
}

export declare function listGameEvents(pathOrBuf: string | Buffer): any

export declare function listUpdatedFields(pathOrBuf: string | Buffer): any

export declare function parseEvent(pathOrBuf: string | Buffer, eventName: string, playerExtra?: Array<string> | undefined | null, otherExtra?: Array<string> | undefined | null, gameEventListBytes?: Buffer | undefined | null): any

export declare function parseEvents(pathOrBuf: string | Buffer, eventNames?: Array<string> | undefined | null, playerExtra?: Array<string> | undefined | null, otherExtra?: Array<string> | undefined | null, gameEventListBytes?: Buffer | undefined | null): any

export declare function parseEventsScoped(pathOrBuf: string | Buffer, scopedEvents: Array<ScopedEventSpec>, gameEventListBytes?: Buffer | undefined | null): any

/**
 * extra: lets you add new fields to grenades. Use list_updated_fields for a full list.
 * grenades: lets you disable non-projectile grenades. This can have a big difference on memory/speed.
 */
export declare function parseGrenades(pathOrBuf: string | Buffer, extra?: Array<string> | undefined | null, grenades?: boolean | undefined | null): any

export declare function parseHeader(pathOrBuf: string | Buffer): any

export declare function parsePlayerInfo(pathOrBuf: string | Buffer): any

export declare function parsePlayerSkins(pathOrBuf: string | Buffer): any

export declare function parseTicks(pathOrBuf: string | Buffer, wantedProps: Array<string>, wantedTicks?: Array<number> | undefined | null, wantedPlayers?: Array<string> | undefined | null, structOfArrays?: boolean | undefined | null, orderBySteamid?: boolean | undefined | null, propStates?: Array<WantedPropState>): any

export declare function parseVoice(pathOrBuf: string | Buffer): Array<VoiceData>

export interface VoiceData {
  tick: number
  data: Buffer
  steamid: string
}

export interface WantedPropState {
  prop: string
  state: JsVariant
}
