/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface VoiceData {
  tick: number
  data: Buffer
  steamid: string
}
export function parseVoice(pathOrBuf: string | Buffer): Array<VoiceData>
export function listGameEvents(pathOrBuf: string | Buffer): any
/**
 * extra: lets you add new fields to grenades. Use list_updated_fields for a full list.
 * grenades: lets you disable non-projectile grenades. This can have a big difference on memory/speed.
 */
export function parseGrenades(pathOrBuf: string | Buffer, extra?: Array<string> | undefined | null, grenades?: boolean | undefined | null): any
export function parseHeader(pathOrBuf: string | Buffer): any
export function parseEvent(pathOrBuf: string | Buffer, eventName: string, playerExtra?: Array<string> | undefined | null, otherExtra?: Array<string> | undefined | null, gameEventListBytes?: Buffer | undefined | null): any
export function parseEvents(pathOrBuf: string | Buffer, eventNames?: Array<string> | undefined | null, playerExtra?: Array<string> | undefined | null, otherExtra?: Array<string> | undefined | null, gameEventListBytes?: Buffer | undefined | null): any
export function parseTicks(pathOrBuf: string | Buffer, wantedProps: Array<string>, wantedTicks?: Array<number> | undefined | null, wantedPlayers?: Array<string> | undefined | null, structOfArrays?: boolean | undefined | null, orderBySteamid?: boolean | undefined | null, propStates?: Array<WantedPropState> | undefined | null): any
export function parsePlayerInfo(pathOrBuf: string | Buffer): any
export function parsePlayerSkins(pathOrBuf: string | Buffer): any
export function listUpdatedFields(pathOrBuf: string | Buffer): any
export declare class JsVariant { }
export declare class WantedPropState {
  prop: string
  state: JsVariant
}
